package server

var Quotes = []string{
	"Never be an insincere friend, never be manipulative, one day you will be discovered and lose everything",
	"A bad friend secretly plots your downfall",
	"Keep quiet and the enemy will reveal himself.",
	"Nothing exists, all is shadow and illusion",
	"If you believe that the world is conspiring against you, it will just do that.",
	"Would a robber break in your home at night beating drums? Nope. This is how those who want to take advantage of your life come: Full of smiles and promising sincere friendship!",
	"Don't tell your friend you are fighting with your wife, it gives him pleasure",
	"Hoarding can never end, for the heart of man always covets for more, its raging appetites can only be quenched by the heavy sands of the grave.",
	"Some beliefs are so strongly held that some believers are ready to lose their heads rather than the belief they carry therein",
	"Home is where you feel more welcome, more secure, have more rights, where you are loved. This place can be any place even away from what you would normally call home.",
	"Don’t fight with your enemy’s brains, fight with his heart",
	"The master doesn’t need to chain his slaves; their needs will chain them to him. You can end slavery by the stroke of a pen, but the pressing call of necessity will reestablish it.",
	"Women’s beauty is a sweet coat to something more sinister- a bribe to men to plunge into the unknown",
	"The greatest thieves are not caught. Not because it’s not known that they are thieves but because you cannot accuse them of robbery and live. These thieves are praised as national heroes and liberators or as successful entrepreneurs.",
	"Only dogs know and respect their masters. This is a rare characteristic of men who secretly envy their masters and wish their downfall.",
	"Riches draw friends as corpses draw vultures",
	"Reason is the beheaded king, emotion the slave revolt",
	"Slaves in the past were captured by force; today’s slaves surrender themselves. The masters are the same old folk (who are now more civilized) who would not lift a hand against a fellow human being! They have established economic systems that perpetuate their superiority so the poor are blamed either for their laziness or their fate.",
	"Those who would give us equal opportunity for everybody are threatened by it. They are afraid to lose their privileged positions. They pay lip service to it, they act by half measures and do everything to violate the laws they have themselves instituted to make sure the high class is always high. It never changes, it always goes in a circle, when the oppressed fight and get to the top, and they become the new elite and forget the promises.",
	"No, it's not advertising; it's mind control",
	"Capitalism: let live who can afford to, not simply who wishes to. Life has a price and it belongs only to those who can pay it.",
	"As long as we build walls around our cities, we make desperate people who want to come in more resolute to bring them down.",
	"At the end of the day you are your own lawmaker",
	"Nature tells the truth as it is; it has no euphemism",
	"Never close your hands in the face of evil fate; get up and rebel against it",
	"It’s not because it’s popular that it is true. The mass doesn’t care about truth; in fact it cherishes carefully crafted lies",
	"The world is like a brute beast, you teach it how it should behave towards you",
	"Unless you have completely destroyed your enemy, your survival is precarious",
	"Neighbor: the nicest enemy you will ever get",
	"People tell all kinds of lies to save their skins.",
}
